version: "3"

volumes:
    logs:
        driver: local

services:
    db:
        image: mariadb
        volumes:
            - container-volume:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: testDatabase
            MYSQL_DATABASE: newcm
        network_mode: "service:api"
    api:
        build: ./api
        ports:
            - "8080:8080"
        expose:
            - 8080
    gui:
        build: ./gui
        ports:
            - "8090:80"
        depends_on:
            - api

volumes:
  container-volume:
