version: "3"

volumes:
    logs:
        driver: local

services:
    db:
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: testDatabase
            POSTGRES_DB: newcm
        ports:
            - "5432:5432"
        expose:
            - 5432
    api:
        image: lonelobo0070/collection_manager_backend:latest
        depends_on:
            - db
        ports:
            - "8080:8080"
        expose:
            - 8080
    gui:
        image: lonelobo0070/collection_manager_frontend:latest
        ports:
            - "8090:80"
        depends_on:
            - api

volumes:
  container-volume:
