version: '3'

volumes:
    logs:
        driver: local

services:
    api:
        build: ./api
        ports:
        - "8080:8080"
    gui:
        build: ./gui
        ports:
        - "80:80"
    db:
        image: mariadb
        volumes:
            - container-volume:/var/lib/mysql
            - ./api/database/database.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
            MYSQL_ROOT_PASSWORD: testDatabase
            MYSQL_DATABASE: newcm
        ports:
        - "3306:3306"
volumes:
  container-volume: