name: Angular build

on:
  push:
    paths: 'gui/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: Angular build
      uses: mayur-rawte/github-angular-actions@latest
      run: |
      ng lint
      ng build --prod
