name: Master docker

on:
  push:
    branches: 
      - master

jobs:
  gui_amd64:
    runs-on: ubuntu-latest
    env:
      working-directory: ./gui
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Remove Cypress dependecy
        working-directory: ${{env.working-directory}}
        run: npm uninstall --save cypress
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: linux/amd64
      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{env.working-directory}}
          push: true
          platforms: linux/amd64
          tags: lonelobo0070/collection_manager_frontend:latest
  gui_arm:
    runs-on: ubuntu-latest
    env:
      working-directory: ./gui
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependecies
        working-directory: ${{env.working-directory}}
        run: npm install
      - name: Install Angular Cli
        working-directory: ${{env.working-directory}}
        run: npm install -g @angular/cli
      - name: Build CM
        working-directory: ${{env.working-directory}}
        run: ng build --configuration production
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: linux/arm64,linux/arm/v7
      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{env.working-directory}}
          push: true
          platforms: linux/arm64,linux/arm/v7
          tags: lonelobo0070/collection_manager_frontend:latest
          file:  ${{env.working-directory}}/Dockerfile_arm
  api:
    runs-on: [ubuntu-latest]
    env:
      working-directory: ./api
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{env.working-directory}}
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: lonelobo0070/collection_manager_backend:latest
