name: Smoke tests

on:
  push:
    branches: 
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch

jobs:
  gui:
    runs-on: ubuntu-latest
    env:
      working-directory: ./gui
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build GUI docker image
        working-directory: ${{env.working-directory}}
        run: docker build .
  api:
    runs-on: ubuntu-latest
    env:
      working-directory: ./api
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build API docker image
        working-directory: ${{env.working-directory}}
        run: docker build .

  tests:
    runs-on: ubuntu-latest
    needs: [gui, api]

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        working-directory: ./gui
        start: docker-compose -f ../docker-compose-e2e.yml up
        wait-on: http://localhost:4200
