name: Smoke tests

on:
  push:
    branches: 
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - uses: KengoTODA/actions-setup-docker-compose@main
      with:
        version: '1.29.2'
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        working-directory: ./gui
        build: docker-compose -f ../docker-compose-e2e.yml build
        start: docker-compose -f ../docker-compose-e2e.yml up
        wait-on: http://localhost:4200
