name: Tests

on:
  push:
    branches: 
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   # excludes master

jobs:
  gui:
    runs-on: ubuntu-latest
    env:
      working-directory: ./gui
      working-directory-api: ./api 

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('gui/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: npm install
      working-directory: ${{env.working-directory}}
      run: npm install
    - name: Use Angular NG
      uses: mayur-rawte/github-angular-actions@latest
    - name: Angular Lint
      working-directory: ${{env.working-directory}}
      run: ng lint
    - name: Angular prod build
      working-directory: ${{env.working-directory}}
      run: ng build --configuration production
    - name: Cypress run
      uses: cypress-io/github-action@v1
      with:
        start: npm run start
        build: npm run e2e
        wait-on: http://localhost:4200
  api:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Unit test + integration tests
        run: mvn --batch-mode --update-snapshots verify --file api/pom.xml
